colorcet 3.0.1
AnacondaRecipes/colorcet-feedstock pull request #2
Opened 2022-11-08 12:54 UTC by skupr-anaconda

Update colorcet to 3.0.1

2022-11-09 08:38 UTC, katietz requested changes

2022-11-09 08:38 UTC, katietz commented on recipe/meta.yaml
> +    - colorcet --help
this recipe has this superflous doc_source_url already ... we should remove it.  there is no value in having it togehter with doc_url.  btw there is also this insane license_url in combination with license_file.  Please remove license_url here too.

2022-11-09 09:09 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - colorcet --help
I addressed your comment

2022-11-09 09:09 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_43zjnc90fk/clone/recipe/meta.yaml:49: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_43zjnc90fk/clone/recipe/meta.yaml:49: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-11-09 09:50 UTC, katietz approved these changes
Thanks!

2022-11-09 22:13 UTC, varlackc approved these changes
LGTM

2022-11-10 12:47 UTC, merged

2022-11-10 12:48 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_731r86_n_d/clone/recipe/meta.yaml:49: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_731r86_n_d/clone/recipe/meta.yaml:49: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>